Smitair3/Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using Smitair3.Data;
using Smitair3.Models;
using SmitairDOTNET.Models;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SmitairDOTNET.Controllers
{
    [Authorize]
    public class PanelController : Controller
    {
        private readonly IHostingEnvironment _hosting;
        public static Effect effects;
        public static Purchase purchases;
        public static bool purchased;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private ApplicationDbContext _context;

        FileStore _store = new FileStore();

        public PanelController(ApplicationDbContext context, IHostingEnvironment hosting,
            UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _hosting = hosting;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            ViewBag.Panel = 1;

            if (_userManager.GetUserId(User) != null)
            {
                var user = _context.Users.Where(us => us.Id == _userManager.GetUserId(User)).Single();

                if (user.AvatarLink != null)
                {
                    string avatarcurrent = _context.Users.Where(us => us.Id == user.Id).Single().AvatarLink;
                    user.AvatarCurrent = _store.UriForImage(avatarcurrent).ToString();
                }
            }
        }

        public ActionResult AddEffect()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEffect([Bind("EffectName,YoutubeLink,Description")]
        Effect effect, Purchase purchase ,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);

                _context.Effects.Add(effect);
                await _context.SaveChangesAsync();

                if (file != null && file.Length > 0)
                {
                    var id = effect.EffectID.ToString();
                    var effectId = await _store.SaveEffect(file.OpenReadStream(), id);
                    effect.EffectLink = effectId;
                }

                effect.YoutubeLink = effect.YoutubeLink.Replace("https://www.youtube.com/watch?v=",
                    "https://www.youtube.com/embed/") + "?ecver=2";

                effect.User = _context.Users.Where(us => us.Id == user.Id).Single();
                _context.Effects.Update(effect);
                await _context.SaveChangesAsync();

                return RedirectToAction("AddEffect");
            }
            return View();
        }

        public async Task<ActionResult> Library()
        {
            var user = await _userManager.GetUserAsync(User);

            var myPurchases = (from x in _context.Purchases
                               where x.User == user
                               select x).Include(y => y.Effect).Include(z => z.Effect.User).ToList();

            return View(myPurchases);
        }

        public async Task<ActionResult> Shop(Guid? idd, Purchase purchase)
        {
            var user = await _userManager.GetUserAsync(User);

            if (idd == null)
            {
                if (purchased) ViewBag.Purchase = "You have bought effect!";
                purchased = false;

                var effects = _context.Effects.Include(x => x.User).ToList();

                return View(effects);
            }
            else
            {
                purchase.User = _context.Users.Where(us => us.Id == user.Id).Single();
                purchase.Effect = _context.Effects.Where(effect => effect.EffectID == idd).Single();

                string effectCurrent = _context.Effects.Where(ef => ef.EffectID == idd).Single().EffectID.ToString();
                purchase.Download = _store.UriForEffect(effectCurrent).ToString();

                _context.Purchases.Add(purchase);
                await _context.SaveChangesAsync();

                purchased = true;
            }

            return RedirectToAction("Shop");
        }
    }
}

Smitair3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"] - Smitair</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Systems of Music Instruments Technology">
    <meta name="author" content="Marcin Horczak & Dawid Nowak">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/scss/style.css" />
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">
    <div class="upper navbar-inverse">
        <div class="logo">
            <img src="~/images/logo.svg">
        </div>
        @await Html.PartialAsync("_LoginPartial")
    </div>

    @if (ViewBag.Panel == 1)
    {
        <div class="rows">
            <div class="container-fluid">
                <div class="row content">
                    @await Html.PartialAsync("_MenuPartial")
                    <div class="col-sm-9">
                        <div class="container body-content">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer style="position:fixed;height:calc(100vh-100px);">
            <p>&copy;SmitairDOTNET - @DateTime.Now.Year</p>
        </footer>
    }
    else
    {
        @RenderBody()
        <footer class="navbar-inverse">
            <p>&copy;SmitairDOTNET - @DateTime.Now.Year</p>
        </footer>
    }

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Smitair3/Views/Shared/_MenuPartial.cshtml
@using Smitair3.Views.Manage
@inject SignInManager<ApplicationUser> SignInManager
@{
    var hasExternalLogins = (await SignInManager.GetExternalAuthenticationSchemesAsync()).Any();
}
<form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm">
    <div class="col-sm-3">

        <ul class="list-group">
            <li class="@ManageNavPages.IndexNavClass(ViewContext) list-group-item"><a asp-controller="Manage" asp-action="Index"><span class="glyphicon glyphicon-user" style="color: #FFFFFF"></span> My Account</a></li>
            <li class="list-group-item"><a asp-controller="Panel" asp-action="Library"><span class="glyphicon glyphicon-book" style="color: #FFFFFF"></span> Library</a></li>
            <li class="list-group-item"><a asp-controller="Panel" asp-action="Shop"><span class="glyphicon glyphicon-shopping-cart" style="color: #FFFFFF"></span> Shop</a></li>
            <li class="list-group-item"><a asp-controller="Panel" asp-action="AddEffect"><span class="glyphicon glyphicon-plus" style="color: #FFFFFF"></span> Add Effect</a></li>
        </ul>

        <div class="panel-group">
            <div class="panel-heading">
                <a data-toggle="collapse" href="#collapse"><span class="glyphicon glyphicon-cog" style="color: #FFFFFF"></span> Settings</a>
            </div>
            <div id="collapse" class="panel-collapse collapse">

                <div class="@ManageNavPages.ChangePasswordNavClass(ViewContext) panel-heading"><a asp-action="ChangePassword">- Change Password</a></div>
                @if (hasExternalLogins)
            {
                    <div class="@ManageNavPages.ExternalLoginsNavClass(ViewContext) panel-heading"><a asp-action="ExternalLogins">- External logins</a></div>
                }
                <div class="@ManageNavPages.TwoFactorAuthenticationNavClass(ViewContext) panel-heading"><a asp-action="TwoFactorAuthentication">- Two-factor authentication</a></div>

            </div>
        </div>
        <ul class="list-group">
            <li class="list-group-item"><button type="submit"><span class="glyphicon glyphicon-off" style="color: #FFFFFF"></span> Logout</button></li>
        </ul>
    </div>
</form>